version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: order_tracking_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db-build-script.sql:/docker-entrypoint-initdb.d/db-build-script.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: order_tracking_web
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
